### ISSUE TITLE
Specify in README what is Pharo version targeted

### ISSUE THREAD

**Issue by juliendelplanque** [kasperosterbye/PillarRichTextRender#1]
Is it expected to work in Pharo 7 as well or only in Pharo 8?

I think it is valuable information.

**Comment by juliendelplanque** [comment]
Apparently does not work in P7, I get a warning about missing dependencies from metacello.

I can provide more details if P7 is targeted. Else this issue can just be closed. :-)

**Comment by kasperosterbye** [comment]
Great - I'll see if I can track that one down. It would be nice if 7 is supported as well, worth for me to spend some time on.

**Comment by kasperosterbye** [comment]
It seems to be a dependency on a Spec2 class. I believe it is a simple issue (in that the tool in question is not needed where it is loaded)

**Comment by kasperosterbye** [comment]
I added a comment in the readme to specify that only Pharo 8 is targeted. I might expand it later.
