### ISSUE TITLE
The following comment makes the image freeze

### ISSUE THREAD

**Issue by juliendelplanque** [kasperosterbye/PillarRichTextRender#3]
```
# Hello
I am an abstract iterator. I define the minimal API that should be understood by any iterator.

- #next returns the next object resulting of walking one step on the underlaying datastructure.
- #peek returns the object that will be returned by #next next time it is called without actually moving on the underlaying datastructure being walked.
- #hasNext returns true if there is a next object available, else returns false.
```

It is possible to unfreeze via `Meta+.` not sure what cause that, this is probably bad pillar but bad pillar code should show an error message in the UI not freeze the image.

This has been done in P8 64 bits latest image.

**Comment by kasperosterbye** [comment]
Interesting - thanks for spotting this one.

**Comment by kasperosterbye** [comment]
It turns out it is the pillar parser, not my visitor that is the problem. I have reduced it to the following string which is the problem: `PRPillarParserMain initialize; parse: '- #uups'`. I'll look into it and see if I can locate the issue in pillar. I will close it here.
